run:
	python3 pokeType_dev.py

venv: # Just use this to get the pathing, then do more research on this later.
	# source ~/projects/virtualEnvironments/pokeTypeVenv/bin/activate
	source /home/adrian/projects/virtualEnvironments/pokeTypeVenv/bin/activate
	