run:
	python3 pokeType.py

input:
	python3 pokeType.py < input.txt

output:
	python3 pokeType.py > output.txt

io:
	python3 pokeType.py < input.txt > output.txt

venv: # Just use this to get the pathing, then do more research on this later.
	# source ~/projects/virtualEnvironments/pokeTypeVenv/bin/activate
	source /home/adrian/projects/virtualEnvironments/pokeTypeVenv/bin/activate
	